apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
spec:
  generators:
    - git:
        repoURL: https://github.com/Follow1985/Chris-try-Day3.git
        revision: main
        files:
          - path: platform/**/config.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      sources:
      - repoURL: '{{ repoURL }}'
        targetRevision: '{{ targetRevision }}'
        chart: '{{ chart }}'
        helm:
          valueFiles:
          - $values/platform/{{ path.basename }}/values.yaml
      - repoURL: https://github.com/Follow1985/Chris-try-Day3.git
        targetRevision: main
        path: platform/{{ path.basename }}
      - repoURL: https://github.com/Follow1985/Chris-try-Day3.git
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: 
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
